name: Continuous Integration

on: pull_request

# - caso queira adicionar mais de um evento:
# on: [pull_request, push, issues]

# - caso queira especificar as branches
# on:
#   pull_request:
#     branches:
#       ['master']

jobs:
  continuous-integration: #nome do job
    runs-on: ubuntu-latest #especificar o sistema operacional que quiser

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: run install, build and test
        run: |
          npm install
          npm run build
          npm run test
